### ISSUE TITLE
Can't import Sofas: "Error downloading model for #XYZ: No model available for #XYZ"

### ISSUE THREAD

**Issue by itaysk** [shish/blender-ikea-browser#9] opened 2024-09-06 15:50 UTC
Search for "Sofa", try to import any sofa, get an error:

Blender log doesn't have useful info just repeating the error:

```
Error downloading model for #50512244: No model available for #50512244
Error downloading model for #40355763: No model available for #40355763
Error downloading model for #00526291: No model available for #00526291
Error downloading model for #40512249: No model available for #40512249
Error downloading model for #10512241: No model available for #10512241
```

Importing other things (e.g a table) worked

**Comment by shish** [comment] 2024-09-07 00:49
Checking the ikea website, none of these products have a 3D model available (these sofas not having models where tables do appears to be a coincidence - so marking as duplicate of #2

**Closed by shish** 2024-09-07 00:49 UTC
